// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/google/wire"
	"os"
)

// Injectors from wire.go:

func initAwsEc2Api(cfg aws.Config) Ec2Api {
	awsEc2Api := NewAwsEc2Api(cfg)
	return awsEc2Api
}

func initMockedEc2Api() Ec2Api {
	mockedEc2Api := NewMockedEc2Api()
	return mockedEc2Api
}

func initAwsEcsApi(cfg aws.Config) EcsApi {
	awsEcsApi := NewAwsEcsApi(cfg)
	return awsEcsApi
}

func initMockedEcsApi() EcsApi {
	mockedEcsApi := NewMockedEcsApi()
	return mockedEcsApi
}

func initAwsRoute53Api(cfg aws.Config) Route53Api {
	awsRoute53Api := NewAwsRoute53Api(cfg)
	return awsRoute53Api
}

func initMockedRoute53Api() Route53Api {
	mockedRoute53Api := NewMockedRoute53Api()
	return mockedRoute53Api
}

// wire.go:

func InitEc2Api(cfg aws.Config) Ec2Api {
	if inTestingMode() {
		return initMockedEc2Api()
	} else {
		return initAwsEc2Api(cfg)
	}
}

func InitEcsApi(cfg aws.Config) EcsApi {
	if inTestingMode() {
		return initMockedEcsApi()
	} else {
		return initAwsEcsApi(cfg)
	}
}

func InitRoute53Api(cfg aws.Config) Route53Api {
	if inTestingMode() {
		return initMockedRoute53Api()
	} else {
		return initAwsRoute53Api(cfg)
	}
}

func inTestingMode() bool {
	return len(os.Getenv("TESTING")) > 0
}

var MockedEc2ApiSet = wire.NewSet(
	NewMockedEc2Api, wire.Bind(new(Ec2Api), new(*MockedEc2Api)),
)

var AwsEc2ApiSet = wire.NewSet(
	NewAwsEc2Api, wire.Bind(new(Ec2Api), new(*AwsEc2Api)),
)

var MockedEcsApiSet = wire.NewSet(
	NewMockedEcsApi, wire.Bind(new(EcsApi), new(*MockedEcsApi)),
)

var AwsEcsApiSet = wire.NewSet(
	NewAwsEcsApi, wire.Bind(new(EcsApi), new(*AwsEcsApi)),
)

var MockedRoute53ApiSet = wire.NewSet(
	NewMockedRoute53Api, wire.Bind(new(Route53Api), new(*MockedRoute53Api)),
)

var AwsRoute53ApiSet = wire.NewSet(
	NewAwsRoute53Api, wire.Bind(new(Route53Api), new(*AwsRoute53Api)),
)
